import {
  blog1,
  blog2,
  blog3,
  client1,
  client2,
  client3,
  client4,
  client5,
  client6,
  product1,
  product10,
  product11,
  product12,
  product13,
  product14,
  product15,
  product16,
  product17,
  product18,
  product19,
  product2,
  product20,
  product3,
  product4,
  product5,
  product6,
  product7,
  product8,
  product9,
  testimonial1,
  testimonial2,
  testimonial3,
  testimonial4,
  testimonial5,
  testimonial6,
} from "./helper";

export const testimonialItems = [
  {
    id: "t1",
    img: testimonial1,
    name: "Lesley Blue",
    quote:
      "My watch got run over by a car, and I was sure nothing could be done to save it. Reprizo proved me wrong, and now my watch looks and works as if nothing happened. Thanks!",
  },
  {
    id: "t2",
    img: testimonial2,
    name: "Jenna West",
    quote:
      "I had a really nice ring that was too loose for my finger but Reprizo resized it in an hour and now it’s a perfect size. Thanks, guys, you’re the best masters!",
  },
  {
    id: "t3",
    img: testimonial3,
    name: "Sam Harrington",
    quote:
      "Reprizo guys have recently repaired my father’s old Rolex. It was fixed within 3-4 days, just as it was initially planned. The service is excellent, I will recommend this company to my friends and colleagues.",
  },
  {
    id: "t4",
    img: testimonial4,
    name: "Mark Normand",
    quote:
      "My watch got run over by a car, and I was sure nothing could be done to save it. Reprizo proved me wrong, and now my watch looks and works as if nothing happened. Thanks!",
  },
  {
    id: "t5",
    img: testimonial5,
    name: "Shelly Gardener",
    quote:
      "I had a really nice ring that was too loose for my finger but Reprizo resized it in an hour and now it’s a perfect size. Thanks, guys, you’re the best masters!",
  },
  {
    id: "t6",
    img: testimonial6,
    name: "John Green",
    quote:
      "Reprizo guys have recently repaired my father’s old Rolex. It was fixed within 3-4 days, just as it was initially planned. The service is excellent, I will recommend this company to my friends and colleagues.",
  },
];

export const blogItems = [
  {
    id: "b1",
    img: blog1,
    date: "26 Jun, 2022",
    title: "What Are the Types of Watch Movements?",
  },
  {
    id: "b2",
    img: blog2,
    date: "26 Jun, 2022",
    title: "Automatic Watches or Quartz Watches?",
  },
  {
    id: "b3",
    img: blog3,
    date: "26 Jun, 2022",
    title: "Best Watches from Top Watchmakers",
  },
];

export const clientItems = [
  {
    id: "c1",
    img: client1,
  },
  {
    id: "c2",
    img: client2,
  },
  {
    id: "c3",
    img: client3,
  },
  {
    id: "c4",
    img: client4,
  },
  {
    id: "c5",
    img: client5,
  },
  {
    id: "c6",
    img: client6,
  },
  {
    id: "c7",
    img: client2,
  },
  {
    id: "c8",
    img: client4,
  },
  {
    id: "c9",
    img: client3,
  },
];

export const productItems = [
  {
    id: "p1",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product1,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p2",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product2,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p3",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product3,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p4",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product4,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p5",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product5,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p6",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product6,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p7",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product7,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p8",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product8,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p9",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product9,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p10",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product10,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p11",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product11,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p12",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product12,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p13",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product13,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p14",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product14,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p15",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product15,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p16",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product16,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p17",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product17,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p18",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product18,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p19",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product19,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
  {
    id: "p20",
    rating: 3,
    discount: 4,
    price: 430.0,
    img: product20,
    priceCrossed: "",
    title: "Fastrack Analog Golden Dial Men’s Watch",
  },
];
